### PR TITLE
Require backports in host & run

### LINKED ISSUE #19: ClobberWarning via simple conda-build recipe
I had raised an issue in `pylint-feedstock` about this (https://github.com/conda-forge/pylint-feedstock/issues/27), and was advised to potentially open an issue here. As I mentioned in that issue, I suppose this could be a `conda-build` problem, but I'm not really sure what's happening; I'm happy to take it up with them with any additional information I might glean here.

Issue:

When I build a simple recipe (details below), I get these warnings/errors:

```
ClobberWarning: This transaction has incompatible packages due to a shared path.
  packages: conda-forge::backports-1.0-py_2, conda-forge::configparser-3.7.1-py27_0
  path: 'lib/python2.7/site-packages/backports/__init__.py'

ClobberWarning: This transaction has incompatible packages due to a shared path.
  packages: conda-forge::backports-1.0-py_2, conda-forge::configparser-3.7.1-py27_0
  path: 'lib/python2.7/site-packages/backports/__init__.pyc'

ERROR:conda.stderr:
ClobberWarning: Conda was asked to clobber an existing path.
  source path: /tmp/miniconda3/pkgs/configparser-3.7.1-py27_0/lib/python2.7/site-packages/backports/__init__.py
  target path: /tmp/miniconda3/conda-bld/foo_1550185030064/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_p/lib/python2.7/site-packages/backports/__init__.py

ERROR:conda.stderr:
ClobberWarning: Conda was asked to clobber an existing path.
  source path: /tmp/miniconda3/pkgs/configparser-3.7.1-py27_0/lib/python2.7/site-packages/backports/__init__.pyc
  target path: /tmp/miniconda3/conda-bld/foo_1550185030064/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_p/lib/python2.7/site-packages/backports/__init__.pyc
```

Here's the recipe:

```
% cat a.py
print

% cat run_test.sh 
/bin/true

% cat meta.yaml 
package:
  name: foo
  version: 0.0.1

requirements:
  build:
    - python
  run:
    - python
    - backports

source:
  path: .

test:
  requires:
    - configparser
  source_files:
    - a.py
```

I am building with

```
conda build -c conda-forge --override-channels .
```

It's a tortured example (the one I gave in the linked-to issue was closer to realistic, requiring `pylint` under `test`), but assuming there's not a reason why I _shouldn't_ be able to do it, it might be a minimal reproducer.
 
<br/>
Environment (<code>conda list</code>):
<details>

```
$ conda list

# packages in environment at /tmp/miniconda3:
#
# Name                    Version                   Build  Channel
asn1crypto                0.24.0                   py37_0  
beautifulsoup4            4.7.1                    py37_1  
bzip2                     1.0.6                h14c3975_5  
ca-certificates           2019.1.23                     0  
certifi                   2018.11.29               py37_0  
cffi                      1.11.5           py37he75722e_1  
chardet                   3.0.4                    py37_1  
click                     7.0                      py37_0  
conda                     4.6.3                    py37_0  
conda-build               3.17.8                   py37_0  
conda-env                 2.6.0                         1  
conda-verify              3.1.1                    py37_0  
cryptography              2.5              py37h1ba5d50_0  
filelock                  3.0.10                   py37_0  
future                    0.17.1                   py37_0  
glob2                     0.6                      py37_1  
icu                       58.2                 h9c2bf20_1  
idna                      2.8                      py37_0  
jinja2                    2.10                     py37_0  
libarchive                3.3.3                h5d8350f_5  
libedit                   3.1.20181209         hc058e9b_0  
libffi                    3.2.1                hd88cf55_4  
libgcc-ng                 8.2.0                hdf63c60_1  
liblief                   0.9.0                h7725739_2  
libstdcxx-ng              8.2.0                hdf63c60_1  
libxml2                   2.9.9                he19cac6_0  
lz4-c                     1.8.1.2              h14c3975_0  
lzo                       2.10                 h49e0be7_2  
markupsafe                1.1.0            py37h7b6447c_0  
ncurses                   6.1                  he6710b0_1  
openssl                   1.1.1a               h7b6447c_0  
patchelf                  0.9                  he6710b0_3  
pip                       19.0.1                   py37_0  
pkginfo                   1.5.0.1                  py37_0  
psutil                    5.5.0            py37h7b6447c_0  
py-lief                   0.9.0            py37h7725739_2  
pycosat                   0.6.3            py37h14c3975_0  
pycparser                 2.19                     py37_0  
pyopenssl                 19.0.0                   py37_0  
pysocks                   1.6.8                    py37_0  
python                    3.7.2                h0371630_0  
python-libarchive-c       2.8                      py37_6  
pytz                      2018.9                   py37_0  
pyyaml                    3.13             py37h14c3975_0  
readline                  7.0                  h7b6447c_5  
requests                  2.21.0                   py37_0  
ruamel_yaml               0.15.46          py37h14c3975_0  
setuptools                40.7.3                   py37_0  
six                       1.12.0                   py37_0  
soupsieve                 1.7.1                    py37_0  
sqlite                    3.26.0               h7b6447c_0  
tk                        8.6.8                hbc83047_0  
tqdm                      4.29.1                     py_0  
urllib3                   1.24.1                   py37_0  
wheel                     0.32.3                   py37_0  
xz                        5.2.4                h14c3975_4  
yaml                      0.1.7                had09818_2  
zlib                      1.2.11               h7b6447c_3  
zstd                      1.3.7                h0b5b093_0  
```
</details>

<br/>
Details about  <code>conda</code> and system ( <code>conda info</code> ):
<details>

```
$ conda info

     active environment : base
    active env location : /tmp/miniconda3
            shell level : 1
       user config file : /home/pmadden/.condarc
 populated config files : 
          conda version : 4.6.3
    conda-build version : 3.17.8
         python version : 3.7.2.final.0
       base environment : /tmp/miniconda3  (writable)
           channel URLs : https://repo.anaconda.com/pkgs/main/linux-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/free/linux-64
                          https://repo.anaconda.com/pkgs/free/noarch
                          https://repo.anaconda.com/pkgs/r/linux-64
                          https://repo.anaconda.com/pkgs/r/noarch
          package cache : /tmp/miniconda3/pkgs
                          /home/pmadden/.conda/pkgs
       envs directories : /tmp/miniconda3/envs
                          /home/pmadden/.conda/envs
               platform : linux-64
             user-agent : conda/4.6.3 requests/2.21.0 CPython/3.7.2 Linux/4.15.0-45-generic ubuntu/18.04.2 glibc/2.27
                UID:GID : 1000:1000
             netrc file : /home/pmadden/.netrc
           offline mode : False

```
</details>

### PR DESCRIPTION
**Pull request by pmspire**
Checklist
* [x] Used a fork of the feedstock to propose changes
* [x] Bumped the build number (if the version is unchanged)
* [x] [Re-rendered]( https://conda-forge.org/docs/conda_smithy.html#how-to-re-render ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [NO] Ensured the license file is being packaged.

As far as I can tell, no `LICENSE` file is present in the existing packages. This PR doesn't change that.

This fixes #19.

### CODE REVIEW

**Comment by jakirkham** [comment]
It seems [the build failure]( https://ci.appveyor.com/project/conda-forge/configparser-feedstock/builds/21903394/job/56ceso5ctvcsq139 ) is causing Python 2.7 to fail on Windows. Note this is the same failure that is affecting Python 3.6. and 3.7 on Windows ( https://github.com/conda-forge/configparser-feedstock/issues/21 ). Could you please update the `skip` to ignore all Windows builds and [re-render]( https://conda-forge.org/docs/webservice.html#conda-forge-admin-please-rerender )? This is not ideal, but the problem looks a bit hairy and may actually be in `pip` or the `configparser` source code, which will require digging into to solve and isn't related to this change.

**Comment by pmspire** [comment]
Updated to skip all Windows builds.

**Comment by jakirkham** [comment]
@conda-forge-admin, please re-render.

**Comment by jakirkham** [comment]
Thanks @pmspire :)

**Pull request merged**
